# Generated by Django 2.1.15 on 2020-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='composer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
